version: "3.8"
services:
  becky:
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    environment:
      - PGHOST=postgres
    volumes:
      - ./secrets:/becky/secrets
  postgres:
    image: postgresql:16
